### PR TITLE
rails 4 compatibility

### PR DESCRIPTION
**Pull request by heartsentwined**
`config.assets.enabled` is gone in rails 4. That means the conditional sprockets engine registration will never get called, because `config.assets.enabled` is always `nil` (by default). This PR replaces this check with rails 4 version check.

I have also swapped out registration on `Sprockets` with `app.assets`. Don't know why, but the former is not working for me.

### CODE REVIEW

**Comment by ghempton** [comment]
Hmm I want to merge this, but not sure what the Travis issue is.

**Comment by heartsentwined** [comment]
The error looks cryptic to me too.

**Comment by heartsentwined** [comment]
Doing a sweeping gem update kind of* solved the problem:

``` sh
$ bundle update
$ rake appraisal:cleanup appraisal:gemfiles appraisal:install
```

Another issue noted from the error messages is to replace

``` rb
source :rubygems
```

with 

``` rb
source 'https://rubygems.org'
```

\* I still get some deprecation warnings.

**Comment by ghempton** [comment]
Can you add those fixes?

**Comment by heartsentwined** [comment]
Oh, sorry, I thought you'd like to try them out first.

**Comment by heartsentwined** [comment]
All fixed now, tests green.

**Comment by ghempton** [comment]
Thanks!!

**Comment by heartsentwined** [comment]
No problem!

**Pull request merged**
